version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:debug
    environment:
      HOST: app
      PORT: 3000
      DB_URL: mongodb://app-mongo/app

    networks:
      - appnetwork
    depends_on:
      - redis
      - mongo

  redis:
    image: redis
    container_name: app-redis
    networks:
      - appnetwork

  mongo:
    image: mongo
    container_name: app-mongo
    networks:
      - appnetwork
    ports:
      - 27017:27017
    restart: always
    volumes:
      - appdata:/data/db

  mongo-express:
    image: mongo-express
    container_name: app-mongo-express
    networks:
      - appnetwork
    restart: unless-stopped
    ports:
      - 443:8081

networks:
  appnetwork:
volumes:
  appdata:
