version: '3.7'

services:
  app:
    container_name: viewer-api-app
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - appnetwork
    depends_on:
      - redis
      - mongo

  redis:
    container_name: app-redis
    image: redis
    networks:
      - appnetwork

  mongo:
    image: mongo
    container_name: app-mongo
    networks:
      - appnetwork
    ports:
      - 27017:27017
    restart: always
    volumes:
      - appdata:/data/db

  mongo-express:
    container_name: app-mongo-express
    networks:
      - appnetwork
    image: mongo-express
    restart: unless-stopped
    ports:
      - 443:8081

networks:
  appnetwork:
volumes:
  appdata:
