name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "viewer-app-api"
          heroku_email: "chris-schilders@hotmail.nl"
          usedocker: true
          docker_build_args: |
            NODE_ENV
        env:
          NODE_ENV: production
